#!/usr/bin/env bash
set -euo pipefail

cat > .env <<'ENV'
CTI_ENVIRONMENT=test
CTI_DATABASE_URL=postgresql+psycopg://cti:cti@postgres:5432/cti
CTI_REDIS_URL=redis://redis:6379/0
CTI_JWT_SECRET=ci-jwt-secret-change-before-real-deployments
CTI_SEEDED_ADMIN_EMAIL=admin@example.com
CTI_SEEDED_ADMIN_PASSWORD=ChangeMe123!
CTI_AI_FIXTURE_MODE=true
CTI_DEEPSEEK_API_KEY=
CTI_DEEPSEEK_MODEL=deepseek-chat
CTI_MISP_URL=https://misp
CTI_MISP_API_KEY=0123456789abcdef0123456789abcdef01234567
CTI_MISP_VERIFY_TLS=false
CTI_MISP_POLL_INTERVAL_SECONDS=60
CTI_SIGMA_TARGET=splunk
CTI_MAX_REPAIR_ATTEMPTS=3
CTI_REASONING_MAX_REVISIONS=3
CTI_REASONING_MIN_IMPROVEMENT_DELTA=0.03
CTI_REASONING_CONFIDENCE_TARGET=0.82
CTI_REASONING_TRUST_TARGET=0.88
CTI_QUALITY_THRESHOLD=75

MISP_BASE_URL=https://localhost:8443
MISP_CORE_HTTP_PORT=8081
MISP_CORE_HTTPS_PORT=8443
MISP_ADMIN_EMAIL=admin@admin.test
MISP_ADMIN_PASSWORD=ChangeMeMisp123!
MISP_ADMIN_KEY=0123456789abcdef0123456789abcdef01234567
MISP_ADMIN_ORG=CTI CI
MISP_EMAIL=misp@localhost
MISP_CONTACT=misp@localhost
MISP_GPG_PASSPHRASE=ci-local-passphrase
MISP_MYSQL_USER=misp
MISP_MYSQL_PASSWORD=example
MISP_MYSQL_ROOT_PASSWORD=password
MISP_MYSQL_DATABASE=misp
MISP_REDIS_PASSWORD=redispassword
ENV

mkdir -p artifacts/security artifacts/docker artifacts/e2e
